[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# Testing
fuzz = { runs = 256 }
invariant = { runs = 256 }

[profile.ci]
fuzz = { runs = 1000 }
invariant = { runs = 1000 }

# RPC Endpoints
[rpc_endpoints]
fuji = "${AVALANCHE_FUJI_RPC_URL}"
mainnet = "${AVALANCHE_MAINNET_RPC_URL}"
madari_l1 = "${MADARI_L1_RPC_URL}"

# Block Explorer Verification
[etherscan]
fuji = { key = "${SNOWTRACE_API_KEY}", url = "https://api-testnet.snowtrace.io/api" }
mainnet = { key = "${SNOWTRACE_API_KEY}", url = "https://api.snowtrace.io/api" }

# Formatting
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
